version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123 # Set the root password
      MYSQL_USER: user123 # Optional: Create a non-root user
      MYSQL_PASSWORD: password123 # Password for the non-root user
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
