version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123 # Set the root password
      MYSQL_USER: user123 # Optional: Create a non-root user
      MYSQL_PASSWORD: password123 # Password for the non-root user
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql-test:
    image: mysql:latest
    container_name: mysql-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root123 # Set the root password
      MYSQL_USER: user123 # Optional: Create a non-root user
      MYSQL_PASSWORD: password123 # Password for the non-root user
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    environment:
      - DATABASE_PATH=/home/dynamodblocal/data

  dynamodb-test:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-test
    ports:
      - "8001:8000"
    volumes:
      - ./dynamodb-test-data:/home/dynamodblocal/data
    environment:
      - DATABASE_PATH=/home/dynamodblocal/data
      - DYNAMODB_ENDPOINT=http://localhost:8001
